name: .NET 9

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET 9
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 9.0.x
    - name: Build with dotnet
      run: dotnet build
    - name: Test with dotnet
      run: dotnet test --no-build -l "junit;LogFilePath=test-results.xml" /p:CollectCoverage=true /p:CoverletOutputFormat=lcov
    - name: Collect coverage
      uses: romeovs/lcov-reporter-action@v0.2.21
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}
        lcov-file: ./tests/coverage.info
    - name: Publish coverage report to coveralls.io
      uses: coverallsapp/github-action@master
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}
        path-to-lcov: ./tests/coverage.info
    - name: Publish Nuget
      run: dotnet build -c Release && dotnet pack -c Release -o out && dotnet nuget push ./out/*.nupkg -s https://api.nuget.org/v3/index.json -k ${{ secrets.NUGETAPIKEY }} --skip-duplicate
    - name: Print test results
      uses: EnricoMi/publish-unit-test-result-action@v1
      if: always()
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        files: tests/test-results.xml
    services:
      zabbix:
        image: zabbix/zabbix-appliance
        ports:
          - 8080:80
          - 10051:10051
